//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserRolesAddedApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int ImageId { get; set; }
        public string ImageName { get; set; }
        public string ImagePath { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public int AddedByUserId { get; set; }
        public Nullable<long> FileSize { get; set; }
        public Nullable<bool> IsLogo { get; set; }
        public string Caption { get; set; }
    }
}
